services:
  - type: web
    name: turno-avem
    runtime: python
    buildCommand: ""
    startCommand: gunicorn turno:app
    envVars:
      - key: FLASK_ENV
        value: production
    plan: professional
